services:
  # Backend API Service
  - type: web
    name: ai-powered-tutoring-system
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_HOST
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false

  # Frontend Web Service
  - type: web
    name: ai-powered-tutoring-system-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ai-powered-tutoring-system.onrender.com
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
